default_language_version:
    python: python3.7

repos:

  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.730
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pipenv run pylint --errors-only
        language: system
        files: src
