version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./.data/db:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    command: run
